
services:
  smart-screen:
    build: ./app
    container_name: ${SMART_SCREEN_CONTAINER_NAME}
    expose:
      - ${SMART_SCREEN_INSIDE_PORT}
    networks:
      - cross-connect-bridge
    restart: always

  screen-nginx:
    build: 
      context: .
      dockerfile: nginxDockerfile
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - ${NGINX_CONTAINER_OUTSIDE_PORT}:${NGINX_CONTAINER_INSIDE_PORT}
    depends_on:
      - smart-screen
    networks:
      - cross-connect-bridge
    volumes:
      - screen_nginx_logs:/var/log/nginx
    restart: always


volumes:
  screen_nginx_logs:
    driver: local


networks:
  cross-connect-bridge:
    name: cross-connect
    driver: bridge